avatarSize="PX_64"
paginationSize=20
showAvatars=true
showBannedBy=true
showDuration=true
showExpiry=true
showHistory=false
showReason=true
showSearch=true
showTotalBans=true
version=1
viewLayout=GRID
